ly_attenuation DV ly_attenuation
ly_down DV ly_down
ly_rayleigh DV ly_rayleigh
recomb2 DV recomb2
sce DV sce
wiremod_angle_xz DV wiremod_angle_xz
wiremod_angle_yz DV wiremod_angle_yz
wiremod_x DV wiremod_x
wiremod_yz DV wiremod_yz

MCstats MCstat
EXTstats EXTstat
BNBstats BNBstat

detVar_total sum 9 ly_attenuation ly_down ly_rayleigh recomb2 sce wiremod_angle_xz wiremod_angle_yz wiremod_x wiremod_yz

DataStats sum 2 EXTstats BNBstats
PredTotal sum 3 detVar_total MCstats EXTstats

total sum 2 PredTotal BNBstats
